apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:                      # stringData = 평문으로 쓰면 K8s가 base64로 저장해줌
  DB_PASSWORD: "boardpass123"
  DB_ROOT_PASSWORD: "rootpass123"