apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
        - name: was
          image: ghcr.io/work-kty/cicd-was:90b56470dd7c07c7d96bbde05f43aa92f808e8c1
#          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:                      # ConfigMap/Secret의 모든 키를 환경변수로 통째 주입
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret