apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/work-kty/cicd-web:3efa18f3b8c812f8dd27dcf1d2821cd54074ea53
          #imagePullPolicy: Never
          ports:
            - containerPort: 80