apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/work-kty/cicd-web:c10f20f003d86fce0b2d7451ed906abb891c12c4
          #imagePullPolicy: Never
          ports:
            - containerPort: 80